name: Update version (On Demand)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (x.y.z):"
        required: true
permissions:
  contents: write

jobs:
  release:
    name: Update version (On Demand)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.3

      - name: Run Update Version
        run: deno task update:version ${{ github.event.inputs.version }}

      - name: Run Update Readme
        run: deno task update:readme

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Version (On Demand)
          commit_options: '--no-verify'
          tagging_message: ${{ github.event.inputs.version }}

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes detected"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes detected"
